config/routes.rb
Rails.application.routes.draw do

    namespace :authentication,path: '',as: '' do
    resources :users,only:[:new,:create] ,path: '/register',path_names:{new:'/'}           #esto creara solo estas accxiones para users
    resources :sessions, only: [:new, :create,:destroy],path: '/login',path_names:{new:'/'}
      end
      resources :favorites,only: [:create,:destroy,:index],param: :product_id
      resources :users, only: :show, path: '/user', param: :username
  resources :categories,except: :show
#resources :products_path resume todas las routes que realizamos anteriormente
  resources :products, path: '/'#con esto hacemos que la pagina siempre inicien en home osea localhost/3000


end

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class='bg-white flex justify-between items-center px-2' data-controller="menu" >
    <%=link_to products_path do%>
        <h1 class=' text-4xl font-bold font-mono text-teal-500 '><%=t('app_name')%></h1>
    <%end%>
    <button class='sm:hidden '  data-action='click->menu#toggle' ><%= image_tag 'icons/menu.svg', width:35,height:35%></button>
    <div class='hidden sm:block'>
    <%=render "shared/items"%>

    </div>
    <! menu movil -->
     
     <div class=' gap-6 sm:hidden absolute bg-white top-0 right-0 shadow z-10 h-full flex flex-col min-w-[35%] overflow-y-scroll ease-in-out duration-200 p-5 translate-x-full' data-menu-target="items">
      <button class='mb-4'  data-action='click->menu#toggle' ><%= image_tag 'icons/close.svg', width:35,height:35%></button>
    <%=render "shared/items"%>
  
    </div>
</div>

app/views/shared/_items.html.erb
<!-  linea 7 me deja ver en la pagina los detalles del Current.user-->
    <%Current.user.inspect%>
    <%=link_to t('.add'),new_product_path, class:'mx-2 text-teal-500 font-bold', data: { turbo_frame: "modal" } if Current.user %>
    <%=link_to t('.favorites'),favorites_path, class:'mx-2 text-teal-500 font-bold' if Current.user %>
    <%=link_to t('.categories'),categories_path, class:'mx-2 text-teal-500 font-bold' if Current.user&.admin?%>
    <%=link_to t('.login'),new_session_path, class:'mx-2 text-teal-500 font-bold' unless Current.user %>
    <%=link_to t('.register'),new_user_path, class:'mx-2 text-teal-500 font-bold' unless Current.user%>
    <%=link_to t('.logout'),session_path(Current.user.id),
        data:{turbo_method: :delete,
            turbo_confirm: t('common.confirm')
                #usamos current para que elimine el usuario dentro de la pagina mas no de la base de datos
            }, class:'mx-2 text-teal-500 font-bold' if Current.user%>