config/routes.rb
Rails.application.routes.draw do

    namespace :authentication,path: '',as: '' do
    resources :users,only:[:new,:create] ,path: '/register',path_names:{new:'/'}           #esto creara solo estas accxiones para users
    resources :sessions, only: [:new, :create,:destroy],path: '/login',path_names:{new:'/'}
      end
      resources :favorites,only: [:create,:destroy,:index],param: :product_id
      resources :users, only: :show, path: '/user', param: :username
  resources :categories,except: :show
#resources :products_path resume todas las routes que realizamos anteriormente
  resources :products, path: '/'#con esto hacemos que la pagina siempre inicien en home osea localhost/3000


end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products, dependent: :restrict_with_exception
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_action :set_category, only: %i[ show edit update destroy ]
  #con esto le decimos que ejecute el metodo set_category antes que el resto de metodos del controlador

  before_action :authorize!
  def index
    # aca no poinemos nada  solopnecesitamos verificar si Current.user es admin
    @categories = Category.all.order(name: :asc)
  end

  # GET /categories/new
  def new

    @category = Category.new
  end

  # GET /categories/1/edit
  def edit

    category
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('.destroyed') }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
    <%= category.name %>
    <%= link_to t('.edit'), edit_category_path(category)%>
    <%= link_to t('.delete'), category_path(category),data:{
      turbo_method: :delete,
      turbo_confirm: t('common.confirm')
    }%>


</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <%@category.errors.full_messages.each do |error|%>
  <div>
    <%=error%>
  </div>
<%end%>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%=t('.title')%></h1>

<%= render "form", category: @category %>



<div>
  
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%=t('.title')%></h1>


<%=render partial: 'category',collection: @categories%>
<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%=t('.title')%></h1>

<%= render "form", category: @category %>



<div>
  <%= link_to t('common.back'), categories_path %>
</div>