config/routes.rb
Rails.application.routes.draw do

    namespace :authentication,path: '',as: '' do
    resources :users,only:[:new,:create] ,path: '/register',path_names:{new:'/'}           #esto creara solo estas accxiones para users
    resources :sessions, only: [:new, :create,:destroy],path: '/login',path_names:{new:'/'}
      end
      resources :favorites,only: [:create,:destroy,:index],param: :product_id
      resources :users, only: :show, path: '/user', param: :username
  resources :categories,except: :show
#resources :products_path resume todas las routes que realizamos anteriormente
  resources :products, path: '/'#con esto hacemos que la pagina siempre inicien en home osea localhost/3000


end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable


  has_one_attached :photo
  validates :title,presence: true
  validates :description,presence: true
  validates :price,presence: true
  belongs_to :category

  belongs_to :user, default: -> { Current.user}#por defecto los productos se asignaran al usuario actual en la sesion
  pg_search_scope :search_full_text, against: {
    title: 'A',#las letras denotan la prioridad de busqueda
    description: 'B'
  }

  ORDER_BY = {
    newest: "created_at DESC",
    expensives: "price DESC",
    cheapest: "price ASC"
  }
  def owner?

    user_id == Current.user&.id
  end

  def broadcast
    broadcast_replace_to self, partial: 'products/product_details', locals: { product: self }
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :protect_pages,only: [:index,:show]
  def index
      #ordena las categorias de manera ascendente
    @categories = Category.order(name: :asc).load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
  end

  def show
    product
  end
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice:  t('.created')#generara un texto en la parte superior de la pagina con el mensaje
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    #obtenemos el producto y llamamos al policie
    authorize! product
  end

  def update
    authorize! product #policie para proteger este producto
    #si clickeamos el boton de actualizar nos redireccionara al index y mostrara un mensaje
    if product.update(product_params)
     product.broadcast
      redirect_to products_path,notice: t('.updated')
    else#si todo sale mal generara un error de estado :unprocessable_entity
      render :edit,status: :unprocessable_entity
    end

  end
  def destroy
    authorize! product
    product.destroy
    redirect_to products_path, notice: t('.destroyed')
  end
  private
  def product
    #buscara por medio de un parametro dinamico (id) el producto que necesite
    #usamos memorization ||=
    @product ||= Product.find(params[:id])#ahora hemos convertido esto en una funcion por lo que podremos llamarlo y aplicar los cambios directamente
  end

  def product_params_index
    #estos son los parametros por los que vamos a filtar a lo largo de la pagina
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by,:page,:favorites,:user_id)
  end
  def product_params
    #restringimos la creacio de los productos segun ciertos parametros obligatorios
    params.require(:product).permit(:title,:description,:price,:photo,:category_id)
  end

 

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_favorite.html.erb
<!  #condicionma de si el producto ya es favorito del usuario o no y dependiendod e eso mostrar una cosa o otra-->
<div id = 'favorite'>
 
  <% if product.favorite%>
    <%= link_to "❌", favorite_path(product.id) , data: {
    turbo_method: :delete
  }  %>
  <%else%>
    <%= link_to "💖", favorites_path(product_id: product.id), data: {
    turbo_method: :post
  }  %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model:@product do |form| %>
<%@product.errors.full_messages.each do |error|%>
  <div>
    <%=error%>
  </div>
<%end%>
  <div>
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>
  <div>
  <%= form.label :description %>
  <%= form.text_area :description %>
  </div>
  <div>
  <%= form.label :price %>
  <%= form.number_field :price %>
  </div>
  <div>
  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>
  <div>
  <%= form.label :photo %>
  <%= form.file_field :photo  %>
  </div>

  <%=form.submit %>
  <%end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product bg-white mb-2 rounded-2xl sm:w-[calc(33.3333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)] italic hover:animate-pulse','data-turbo-frame' => '_top' do %>
    <!image_tag product.photo.attached? ?  product.photo : 'placeholder.jpg' -->
     <! estructura                      ?if                :else -->
    <%= image_tag product.photo.attached? ?  product.photo : 'noimage.jpg', class:'w-full h-60 object-cover'  %>
    <div class="m-2">
    <span class="font-bold text-xl"><%= product.price %>$</span>
    <h2><%= product.title %></h2>
    <p class="text-gray-300 font-serif text-sm mt-2"><%= product.description %> </p>
    </div>
    
<% end %>
  

app/views/products/_product_details.html.erb
<div id="<%= dom_id(product) %>">
  <%= image_tag product.photo, width: 200 if product.photo.attached? %>

  <h1 class='title text-3xl text-bold p-4 font-mono font-bold'><%= product.title %></h1>

  <p class='description '><%= product.description %></p>

  <span class='price'><%= product.price %>$</span>
</div>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>
<h2><%=t('.title')%></h2><!-- Ruta relativa controlador.accion.objeto_a_cambiar el ya supone los dos anteriores -->
<%=render 'form'%>

app/views/products/index.html.erb
<%=turbo_frame_tag 'home' do %>
    
     <%= form_with url:  products_path,method: :get do |form| %>
     
     <%=form.text_field :query_text,placeholder: t('.query_text'),onchange: ' this.form.requestSubmit()',value: params[:query_text],class:'w-full my-2 rounded-2xl border-gray-200' %>
        <div class='flex'>
            <%=form.number_field :min_price,placeholder: t('.min_price'), onChange: ' this.form.requestSubmit()',value: params[:min_price],class:'w-1/3   rounded-2xl border-gray-200'%>
            <%=form.number_field :max_price,placeholder: t('.max_price'), onChange: ' this.form.requestSubmit()',value: params[:max_price],class:'w-1/3 mx-2  rounded-2xl border-gray-200'%>
     
            <!-- options_for_select(aca recibe como parametro un hash o un array bidimensional el primer parametro es el label que se muestar en la pagina yel segundo su valor que se envia en el formulario) -->
           
            <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order] }, params[:order_by]),{},{onchange: ' this.form.requestSubmit()', class: "w-1/3 rounded-2xl border-gray-200 text-gray-500"}%> 
        <%end%>
         </div>
         <! renderizar el component de categorias-->
          <div class="flex overflow-x-scroll gap-2 my-4 hover:animate-bounce ">
       <%= render(CategoryComponent.new) %>
       <%= render(CategoryComponent.with_collection(@categories)) %>
        </div>
          
    <!--#la linea 18 establece que este turbo frame tag se llama :products-->
    <%=turbo_frame_tag :products,class:'flex flex-col m-2 ' do %>
        <%= turbo_frame_tag "products-#{@pagy.page}", class: ' products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2  ' do %>
            <%= render partial: 'product', collection: @products %>
            <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products flex flex-col w-full  sm:flex-row sm:flex-wrap sm:gap-x-2', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
        <%end%>
    <%end%>

<%end%>

app/views/products/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">
      <p class="cursor-pointer mb-4" data-action="click->modal#close">❌</p>
      <h2 class="font-bold mb-4"><%= t('.title') %></h2>

         <%= render 'form' %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<%= render partial: 'products/product_details', locals: { product: @product } %>


<%= link_to 'Editar producto', edit_product_path(@product) if @product.owner? %>

<%= link_to 'Eliminar producto', product_path(@product), data: {
  
  turbo_method: :delete,
  turbo_confirm: t('common.confirm')
} if @product.owner? %>

<%= link_to t('.view_more_products', username: @product.user.username), user_path(@product.user.username)%>
<%= render partial: 'favorite',locals: {product: @product}%>

<%= turbo_stream_from @product %>